# Generated by Django 4.2.5 on 2023-11-05 17:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
